import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My Post
        </h1>

        <ul className={styles.posts}>
          <li>
            <p className={styles.postsContent}>
              Este é um novo post de teste no meu projeto de posts de mensagens.
            </p>
            <p className={styles.postsDate}>
              04/05/2021
            </p>
          </li>
          <li>
            <p className={styles.postsContent}>
              Este é um novo post de teste no meu projeto de posts de mensagens.
            </p>
            <p className={styles.postsDate}>
              04/05/2021
            </p>
          </li>
          <li>
            <p className={styles.postsContent}>
              Este é um novo post de teste no meu projeto de posts de mensagens.
            </p>
            <p className={styles.postsDate}>
              04/05/2021
            </p>
          </li>
        </ul>

        <form>
          <textarea className={styles.postsTextArea}></textarea>
          <button className={styles.postsButton}>Add New Post</button>
        </form>

      </main>        
    </div>
  )
}
