import Head from 'next/head';

import { useAuth } from '../hooks/useAuth';

import Bio from '../components/Bio';
import Post from '../components/Post';
import PostForm from '../components/PostForm'

import styles from '../styles/Home.module.scss';

export default function Home() {

  const { user, logIn, logOut } = useAuth();

  console.log('user', user);

  return (
    <div className={styles.container}>
      <Head>
        <title>My Post Sistem</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      { !user && (
        <p>
          <button onClick={logIn}>Log In</button>
        </p>
      )}
      
      { user && (
        <p>
          <button onClick={logOut}>Log Out</button>
        </p>
      )}

      <main className={styles.main}>
        
      <Bio
        headshot="https://pbs.twimg.com/profile_images/1284323790692978689/TXV_s_Sd_400x400.jpg"
        name="Mauricio Mikulski"
        tagline="Helping others to learn by doing!"
        role="Student Developer @dwlove"
      />

        <ul className={styles.posts}>
          <li>
            <Post
              content="Hey, I'm a new post!" date="06/05/2021" />
          </li>
          <li>
            <Post
              content="This is a new test post in my post project."            
              date="04/05/2021"
            />
          </li>
          <li>
            <Post
              content="This is a new test post in my post project."            
              date="04/05/2021"
            />
          </li>
          <li>
            <Post
              content="This is a new test post in my post project."            
              date="04/05/2021"
            />
          </li>
        </ul>

        { user && (
          <PostForm />
        )}
        
      </main>        
    </div>
  )
}
